<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Account Number_bank_account_detail-ba_877885</name>
   <tag></tag>
   <elementGuidId>c9fb4730-4c7c-44ea-9b09-e3127240db32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='bank_account_detail-bank_account_number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#bank_account_detail-bank_account_number</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Input Account Number&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d72dae97-d09f-4aa4-83cf-31f80ddea243</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>7b594897-e4b9-47dc-915b-d30d89b2250f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5c128605-e935-48dd-832b-d9b3b1892fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>bank_account_detail-bank_account_number</value>
      <webElementGuid>d963d933-86d7-428d-b2fb-dbb7c6d94a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bank_account_number</value>
      <webElementGuid>5bb4d808-6761-4f1b-9ad2-5531a7dcafa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Account Number</value>
      <webElementGuid>e8b1f0b9-758b-451a-8aad-dab1cb5104a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bank_account_detail-bank_account_number&quot;)</value>
      <webElementGuid>710a41c6-b71e-4ad8-8a3b-38b9d244e7a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='bank_account_detail-bank_account_number']</value>
      <webElementGuid>0d66505d-e194-4171-90c7-d207e229c5d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='bank-account-form']/div[2]/div/input</value>
      <webElementGuid>f9a2e752-2252-421d-a671-ba200340b143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3faca21d-c7e1-4d83-915c-c2d609c180ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'bank_account_detail-bank_account_number' and @name = 'bank_account_number' and @placeholder = 'Input Account Number']</value>
      <webElementGuid>36232225-05d6-46cc-8b3a-6dd075f85659</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
